spring:
  application:
    name: mpdemo


  datasource:
    url: jdbc:mysql://localhost:23306/mpdemo?useSSL=false&serverTimezone=UTC
    username: root
    password: root5744
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.schoz.mpdemo.user.entity

server:
  port: 8081


